services:
  # octane:
  #   image: serversideup/php:8.4-cli-alpine
  #   command: >
  #     sh -c "php /var/www/html/artisan octane:install --server=frankenphp -n &&
  #     php /var/www/html/artisan octane:start --server=frankenphp -n"
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PHP_POST_MAX_SIZE=500M
  #     - PHP_UPLOAD_MAX_FILE_SIZE=500M
  #     - PHP_OPCACHE_ENABLE=1

  franken:
    image: dunglas/frankenphp
    volumes:
      - .:/app
    ports:
      - "8000:80"

  task:
    image: serversideup/php:8.4-cli-alpine
    # command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    volumes:
      - .:/var/www/html
    depends_on:
      - octane

  queue:
    image: serversideup/php:8.4-cli-alpine
    # command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    stop_signal: SIGTERM
    volumes:
      - .:/var/www/html
    depends_on:
      - octane